# conf/config.yaml
mysql:
  localhost: 127.0.0.1
  port: 3306
  user: root
  password: root
  database: dragonfly

wechat:
  appid: wx9fea5106cf08d1ee
  secret: 5ce6ac99cde2f56b392624d118ec4393


domain: http://192.168.2.111:8080

