# conf/config.yaml
mysql:
  localhost: 111.229.109.208
  port: 3306
  user: dragonfly
  password: dragonfly
  database: dragonfly

channel:
  num: 10
  hour: 5

wechat:
  appid: wx9fea5106cf08d1ee
  secret: 5ce6ac99cde2f56b392624d118ec4393
  mchId: 1626666582
  key: 957B9F367701C77F6F68D511A5C51B10

port: 9090

vip_default_level: G0

#domain: http://192.168.2.111:9090
domain: https://dragonfly.sszi.cc

